### PR TITLE
Ju finishing backend

### PR DESCRIPTION
**Pull request by sophiachiao**

### CODE REVIEW

**Review by jukim98 — APPROVED** [review]
sambuca

**Review by huypham048 — APPROVED** [review]
SAMBUCA

**Review by BiancaPicasso — APPROVED** [review]
these controllers are amazing

**Review by huypham048 — APPROVED** [review]
SAMBUCA

**Review by SalSaluga — APPROVED** [review]

**Review by BiancaPicasso — APPROVED** [review]

**Pull request merged**
